services:
  ai_assistant_core:
    build:
      context: ai_assistant_core
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ENVIRONMENT=docker
    volumes:
      - ./ai_assistant_core:/srv/ai_assistant_core
      - ai_assistant_core-repos:/srv/ai_assistant_core/repos
      - ./service-config.yaml:/srv/ai_assistant_core/service-config.yaml
    networks:
      - app-network
    profiles:
      - ai_assistant_core

  auth_rbac_service:
    build:
      context: auth_rbac_service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - ENVIRONMENT=docker
      - HOST=0.0.0.0
    volumes:
      - auth_rbac_service-repos:/srv/auth_rbac_service/repos
    networks:
      - app-network
    profiles:
      - auth_rbac_service

  billing_payments_service:
    build:
      context: billing_payments_service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - ENVIRONMENT=docker
      - HOST=0.0.0.0
    volumes:
      - billing_payments_service-repos:/srv/billing_payments_service/repos
    networks:
      - app-network
    profiles:
      - billing_payments_service

volumes:
  ai_assistant_core-repos:
  billing_payments_service-repos:
  auth_rbac_service-repos:

networks:
  app-network:
    driver: bridge
