services:
  ai-assistant-core:
    build:
      context: ./ai-assistant-core
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ENVIRONMENT=docker
    volumes:
      - ./ai-assistant-core:/srv/ai-assistant-core
      - ai-assistant-core-repos:/srv/ai-assistant-core/repos
      - ./service-config.yaml:/srv/ai-assistant-core/service-config.yaml
    networks:
      - app-network
    profiles:
      - ai-assistant-core

  auth-rbac-service:
    build:
      context: auth-rbac-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - ENVIRONMENT=docker
      - HOST=0.0.0.0
    volumes:
      - auth-rbac-service-repos:/srv/auth-rbac-service/repos
    networks:
      - app-network
    profiles:
      - auth-rbac-service

  billing-payments-service:
    build:
      context: billing-payments-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - ENVIRONMENT=docker
      - HOST=0.0.0.0
    volumes:
      - billing-payments-service-repos:/srv/billing-payments-service/repos
    networks:
      - app-network
    profiles:
      - billing-payments-service

volumes:
  ai-assistant-core-repos:
  billing-payments-service-repos:
  auth-rbac-service-repos:

networks:
  app-network:
    driver: bridge
