# Basic configuration for the service
# Add your specific configuration details here

service:
  name: ai-assitant-core
  version: 1.0.0
  description: Configuration for the ai-assitant-core service

billing-payments-service:
  name: billing-payments-service
  version: 1.0.0
  description: Configuration for the billing-payments-service service

auth-rbac-service:
  name: auth-rbac-service
  version: 1.0.0
  description: Configuration for the auth-rbac-service service

# Add more configuration options as needed for each service 