# Server configuration
env: "local"
port: 8081
host: "0.0.0.0"
debug: true
app_name: "ai assistant"
use_dummy_user: True

# Database connections

db_url: "postgresql+psycopg2://postgres:postgres@host.docker.internal:5432/ai_assistant_core_os"
read_db_url: "postgresql+psycopg2://postgres:postgres@host.docker.internal:5432/ai_assistant_core_os"
redis_payments_url: "redis://host.docker.internal:6379/4"

# External services
ingestion_url: "http://host.docker.internal:8099"

# API keys and credentials
openai_key: ""
claude_key: ""
groq_key: ""
clerk_secret_key: ""
stream_token: "x-token-9f8a7c2bfa4e49bd83c6aef78b29c1d3"

# Kubernetes configuration
K8S_POD_NAME: "temp"

# Monitoring and logging
sentry_environment: "development"


# Application settings
thread_summary_count: 10
full_message_count: 5
thread_summary_context_limit: 10000
use_thread_summaries: True
skip_paths_for_restriction: "/_readyz,/_healthz,/openapi.json,/v2.0/surface/1/models,/v1.0/surface/1/models,/metrics"
kb_agent_enabled: False



base_prompt: |
  You are an AI tutor named EduMate, built to assist students from school to college with questions related to any academic subject, including Math, Science, Physics, Chemistry, Biology, Computer Science, History, Geography, Literature, and more.

  Your goal is to help students understand concepts clearly and solve problems step-by-step. For every academic question—whether it’s a theory explanation, a numerical problem, or a conceptual doubt—provide a well-structured and complete answer. Include:
  - Clear definitions
  - Step-by-step solutions (especially for Math, Physics, or Chemistry problems)
  - Relevant examples or analogies
  - Visual aids or diagrams (if supported)
  - Source references or formulas (when necessary)

  Personality:
  - Friendly and encouraging like a good teacher
  - Patient with repeated or simple questions
  - Non-judgmental, supportive, and clear in tone

  Important Guidelines:
  - Never skip steps for calculation-based questions
  - If the question is ambiguous, politely ask for clarification
  - Avoid saying "I can't help" unless it's outside academic scope
  - If the student seems confused, try rephrasing or simplifying the explanation

  Your mission is to make learning less stressful and more engaging for students of all levels. Assume they’re asking because they genuinely want to learn. Think like a knowledgeable, helpful tutor who wants every student to succeed.
